// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC25VQEH4EWvLOqMLxe7aIqIb0OiauXgs0',
    appId: '1:185865959604:web:3d8846d0bb70de54e07fe1',
    messagingSenderId: '185865959604',
    projectId: 'testing56-c93b2',
    authDomain: 'testing56-c93b2.firebaseapp.com',
    storageBucket: 'testing56-c93b2.appspot.com',
    measurementId: 'G-SLZWB3DB32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYbHtj2vHxLDyVgIQBGmB7ivLf8_MU87I',
    appId: '1:185865959604:android:75da3acb83b32ca7e07fe1',
    messagingSenderId: '185865959604',
    projectId: 'testing56-c93b2',
    storageBucket: 'testing56-c93b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQNkdTgxjD6SSWkfpZx7H8010Zvr7Jtv0',
    appId: '1:185865959604:ios:c7b6110f82a667ebe07fe1',
    messagingSenderId: '185865959604',
    projectId: 'testing56-c93b2',
    storageBucket: 'testing56-c93b2.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQNkdTgxjD6SSWkfpZx7H8010Zvr7Jtv0',
    appId: '1:185865959604:ios:c7b6110f82a667ebe07fe1',
    messagingSenderId: '185865959604',
    projectId: 'testing56-c93b2',
    storageBucket: 'testing56-c93b2.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC25VQEH4EWvLOqMLxe7aIqIb0OiauXgs0',
    appId: '1:185865959604:web:8d2d53ebfe8e8d9be07fe1',
    messagingSenderId: '185865959604',
    projectId: 'testing56-c93b2',
    authDomain: 'testing56-c93b2.firebaseapp.com',
    storageBucket: 'testing56-c93b2.appspot.com',
    measurementId: 'G-2734BJ4Z7Y',
  );
}
